name: Test kadai1.py

on:
  push:
    branches:
      - main  # main ブランチへの push でトリガー

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]  # 複数の Python バージョンでテスト

    steps:
      - uses: actions/checkout@v3  # リポジトリのコードをクローン

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # 使用する Python のバージョン

      - name: Grant execute permissions to the script
        run: chmod +x kadai1.py  # kadai1.py に実行権限を付与

      - name: Run the script with input
        run: echo "100 10" | ./kadai1.py > output.txt  # 標準入力を渡して実行

      - name: Check output
        run: |
          output=$(cat output.txt)
          expected="速さ: 10.0 メートル/秒"
          if [[ "$output" != "$expected" ]]; then
            echo "Test failed: got '$output', expected '$expected'"
            exit 1
          else
            echo "Test passed: $output"
